### ISSUE TITLE
`@media print` doesn't work when calling `window.print` in Chrome

### ISSUE THREAD

**Issue by bobbyrenwick** [FormidableLabs/radium#132]
I have made a [jsbin](http://output.jsbin.com/jequceropa/9) to demonstrate the behaviour. When pressing `cmd + p`, both the Radium styled text and the CSS styled text turn red. But when you press the print button, only the CSS styled text turns red.

It seems to be related to the difference between calling `window.print` in JS and pressing `cmd + p` in Chrome.

At the moment I am working around this by having a flux store that listens to `matchMedia` changes, and an action to explicitly set the state.

```js
function print() {
    PrintStateActionCreators.clickedPrint();
    _.defer(() => print());
};
```

```js
window.matchMedia("print").addListener((mql) => {
    this.state = this.state.set("printing", mql.matches);
    this.emitChange();
});
```

The `defer` is the key, because it gives React time to rerender the DOM, given the new styling. This solution is somewhat lacking though because the user will see the print styled component behind the print preview dialog. Any suggestions for how I could avoid this situation?

**Comment by ianobermiller** [comment]
Here is an updated bin that uses font-weight instead since it is easier to see: http://jsbin.com/guzul/3/edit?html,css,js. Its also not anonymous, so it won't time out.

I did some more digging, and this problem is not unique to Radium; it occurs whenever you update the document asynchronously in response to matchMedia for `@media print`. Since React's render calls are always batched, you need the defer as you've found out. The thing is, browsers are not consistent. Using the above jsbin:

Is "Test Radium" bold? (all testing on Mac)

Browser | <kbd>cmd+p</kdb> | PRINT button | PRINT defer button
------|-----|-----|----|-----
**Chrome** | :x: | :x: | :white_check_mark: 
**Firefox** | :x: | :x: | :x: 
**Safari** | :white_check_mark: |:x: (see note) | :x: (see note)

Note: Safari doesn't support `window.print`

Unfortunately, it looks like this is a limitation of inline styles : (. We should add this to the readme.

**Comment by bobbyrenwick** [comment]
Thanks for doing some more digging. That's pretty thorough!

There was one way I was thinking of working around it by making the new `Style` component able to render media queries, rather than just classes. That way we could keep all the logic within the components?

**Comment by alexlande** [comment]
That's really interesting. I can't believe we don't call this out in the docs (and will rectify that soon), but the `Style` component can do media queries: https://github.com/FormidableLabs/radium/blob/master/examples/app.jsx#L84-L116

This is another good point for handling media queries with `style` elements as in https://github.com/FormidableLabs/radium/issues/53 though.

**Comment by bobbyrenwick** [comment]
@alexlande that's great news that the `Style` component can do media queries. I'll try using that and see where that takes me. Thanks!

**Comment by ianobermiller** [comment]
Added a comment about `@media print` to the docs in #135.
