### ISSUE TITLE
Unsupported CSS property 'filter'

### ISSUE THREAD

**Issue by mrtnbroder** [FormidableLabs/radium#161]
It would be nice to have the css property `filter` http://caniuse.com/#feat=css-filters
added to the prefixer.js

Maybe switch to autoprefixer instead of using a selfmade version?

**Comment by ianobermiller** [comment]
What browser and version are you testing, and what exactly is your code? The error message in the title is odd, because `filter` is a property, not a value.

Autoprefixer is only appropriate for server-side situations; it is far too large to ship to the client, and of course there is no reason to send all the prefixing information for other browsers. Radium's prefix fuctionality is based on [css-vendor](https://github.com/jsstyles/css-vendor), and does in-browser detection for which properties and values require prefixes.

**Comment by mrtnbroder** [comment]
Sorry, I meant property, not value.

I'm using Chrome latest.

**Comment by mrtnbroder** [comment]
Code looks like that:

```javascript

class MyElement extends React.Component {

  constructor(props) {
    super(props)
  }

  render() {
    return (
      <img
        style={[
          styles.base
        ]}
        src={this.props.srcUrl}
        />
    );
  }
}

var styles = {
  base: {
    filter: 'blur(4px)'
  }
};

module.exports = Radium.Enhancer(MyElement);
```

**Comment by ianobermiller** [comment]
Ugh, stupid chrome. Apparently the `filter` property exists in the style object, but only works if you set it using the prefix.
