### ISSUE TITLE
computed variables value proposition

### ISSUE THREAD

**Issue by colinmegill** [FormidableLabs/radium#21]
Regarding variables - maybe you want them darker or lighter on different media, so you could take in user agent string and then return different variables in the store for colors, things like that, *if* we use a store for styles and put the variables there, rather than just using a module and returning an object.

**Comment by alexlande** [comment]
The dynamic variable idea is pretty cool, but I think the use cases are sort of limited. They are very cool use cases though. Dynamic color schemes based on user input!

That said-- not convinced that this belongs in Radium core for that reason, especially because I don't want people to get the impression that they should *always* handle variables that way, when in general the easiest thing to do is require an object where your app-wide variables are defined.

Maybe the first radium plugin?

/cc @colinmegill @rgerstenberger

**Comment by colinmegill** [comment]
@alexlande how would our conversation on `context` in react factor into this?

**Comment by alexlande** [comment]
I would expect it to use `context` the same way that the match media mixins do.

I would be hesitant to recommend that for static variables though as there is some performance overhead. Would be a little more convenient than importing your variables wherever they're used, but I would generally think that slightly more typing is worth it so that you don't affect performance more than necessary.

**Comment by colinmegill** [comment]
First, totally agree that static variables are easiest and should be default. Second, what do you think about encouraging this as a _pattern_, maybe it's more of a blog post and we see what gets done with it and where there are asks?

**Comment by colinmegill** [comment]
(should also clarify for posterity that _value prop_ in the title is Value Proposition -  props is a little overloaded now :)

**Comment by alexlande** [comment]
Maybe? It should be easy to implement, and until `context` is documented and finalized it might be nice to hide that complexity by wrapping it up as a mixin people can use.

**Comment by colinmegill** [comment]
Ok fully support mixin and really excited about this (was playing devil's advocate to see if we could de-prioritize for now).

It seems to me like completing the loop - how something looks is based on data (global style variables like colors/fonts/margins) that is computed by components. It's powerful to reverse that and say that the data (global style variables like colors/fonts/margins) can themselves change given their environment and application state. 

I **know** we would have used that functionality in the past if we had had it when we hit cross device problems. Being able to change global style variables based on things like user agent or device pixel ratio would have been really clean.

**Comment by ianobermiller** [comment]
Is this still relevant? Is there anything proposed to implement into Radium? Please reopen if so.
