### ISSUE TITLE
Remove warnings for supplying array to 'style' prop

### ISSUE THREAD

**Issue by NBallaney** [FormidableLabs/radium#249]
![image](https://cloud.githubusercontent.com/assets/8469211/8575318/377645b0-2550-11e5-927d-ca47a39cf0f9.png)

I am supplying an array to prop 'style' to allow for interactive CSS, as mentioned in the README. But I keep getting these warnings from React in the console.

**Comment by ianobermiller** [comment]
That's a React warning, and it means Radium is not getting run on that element. Can you provide some more code?

**Comment by NBallaney** [comment]
Radium is running on that element as I can see its effects. The element in point though is a Material UI component (https://github.com/callemall/material-ui). The warning does not occur for non Material UI elements. 
Here's how I'm using it. ListItem is a Material UI component:
`
                    <ListItem ref={"dashboard"}
                              style={[
                                  styles.item,
                                  selected === "dashboard" && styles.itemSelected
                              ]}
                              onTouchTap={this._goToDashboard}>
`

**Comment by ianobermiller** [comment]
Ah yes, that is a deliberate decision on our part, not to mess with the style prop of non-DOM elements. Otherwise bad things can happen, like #202. We shouldn't make any assumptions about how the style prop of a custom component is used. For your case, since you can't pass anything Radium specific to the component anyway (since it isn't using Radium internally), you can just use Object.assign:

```as
<ListItem
  ref="dashboard"
  style={Object.assign(
    {},
    styles.item,
    selected === 'dashboard' && styles.itemSelected
  )}
  onTouchTap={this._goToDashboard}
/>

**Comment by NBallaney** [comment]
This is awesome. Thank you!
