### ISSUE TITLE
Unable to use getState for 0th indexed list items

### ISSUE THREAD

**Issue by joshblack** [FormidableLabs/radium#275]
I am trying to use the `getState` method when dealing with a list of items but am running into an issue when trying to get the state of `0th` indexed items. For example:

```js
import Radium from 'radium';
import { Component } from 'react';

@Radium
class List extends Component {
  render() {
    // Always false
    console.log(Radium.getState(this.state, 0, ':hover'));
    
    return (
      <ul>
        {
          this.props.items.map(
            (item, i) => <li key={i} style={styles.item}>{item}</li>)
        }
      </ul>
    );
  }
}

const styles = {
  item: {
    ':hover': {
      background: 'pink'
    }
  }
};
```

The `getState` method works perfectly for any item above 0, for example if I change the above to:

```js
{
  this.props.links.map(
    (item, i) => <li key={i + 1} style={styles.linkItem}>item</li>)
}
```

And use `getState` on the first item in the list (1) then the method works perfectly. Is this the intended use case or am I doing something wrong with the first example?

**Comment by ianobermiller** [comment]
Its because you are passing numbers instead of strings, and 0 is falsey. [This statement, `elementKey = elementKey || 'main'; `](https://github.com/FormidableLabs/radium/blob/88d523c36ecfaf8d86a4e612a2d00cb2d1415c5b/modules/get-state.js#L10) will cause the key to become main, which is what makes it not work. As a short term fix, you can change `0` to `'0'`, and I'll send a PR to change the code to `elementKey = elementKey === undefined || elementKey === null ? 'main' : elementKey;`, which will fix the general issue.
