### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function, not object

### ISSUE THREAD

**Issue by eriklharper** [FormidableLabs/radium#341]
I'm getting this error out of the gate when attempting to use Radium in my project:

![image](https://cloud.githubusercontent.com/assets/821864/9647619/f454456e-5193-11e5-994b-6d61eadda18e.png)

At the top of my root-level app.js component, I'm requiring it with: 

```
var Radium = require('radium');
```

Then down below in my render, I'm using it like so:

```
render: function () {
return Radium(
      <div id="appContainer" style={appContainerStyle}>
        <section id='app' style={appStyle}>
          {content}
        </section>
      </div>
    );
}
```

Not sure if I'm using it right.  I'm not using ES6, and just creating React classes with createClass.  Using React 0.13.3

**Comment by alexlande** [comment]
Hey @eriklharper, looks like your issue is that you're wrapping the wrong thing with `Radium`. Rather than wrapping the elements returned by your component's `render` method, you should wrap the entire component.

You can find documentation on usage here: https://github.com/FormidableLabs/radium/tree/master/docs/api#radium

With `createClass`, usage should look like this:

```
var MyComponent = React.createClass({ ... });
MyComponent = Radium(MyComponent);
```

**Comment by eriklharper** [comment]
Thanks @alexlande you are totally right.  Soon after I posted this issue, I figured that out exactly.  My render return statement looks like normal now, and I figured out that I had to refactor my React.render function from this:

```
React.render(<App />, document.getElementById('ReactRenderTarget'));
```
to this:
```
React.render(React.createElement(Radium(App)), document.getElementById('ReactRenderTarget'));
```
Works great now, thanks!
