### ISSUE TITLE
Radium mask prefix

### ISSUE THREAD

**Issue by samloomes** [FormidableLabs/radium#342]
Converting my app to use Radium for styling, I think the prefixer is changing mask to -webkit-mask which is killing it. It wasn't happening before with Webpack/Autoprefixer.

Any ideas/overrides?

Cheers!

**Comment by ianobermiller** [comment]
Interesting; the prefixer basically checks existing style objects for fields, and if it doesn't find them, checks for the prefixed version. We plan to move away from this type of prefixing in the future, since it doesn't work on the server. 

Looking into your case more, prefixer chooses the prefixed version over the unprefixed version (due to other incompatibilities), which is why `webkitMask` is being used instead of `mask`. Do they behave differently?

**Comment by ianobermiller** [comment]
Fixed with use of inline-style-prefixer.
