### ISSUE TITLE
Radium throws error on using callback refs

### ISSUE THREAD

**Issue by azazdeaz** [FormidableLabs/radium#346]
Hi! Radium throws this error if it finds callback ref in multiple children:
*Uncaught Error: Radium requires each element with interactive styles to have a unique key, set using either the ref or key prop. Key "function () {}" is a duplicate.*
[JSBin demo about this](http://jsbin.com/vemofu/edit?html,js,console)

I'm not sure what would be the good solution for this, maybe Radium could just use the ```key``` and child index as a fallback [here](https://github.com/FormidableLabs/radium/blob/master/modules/resolve-styles.js#L381).

**Comment by ianobermiller** [comment]
Yes, if the ref is a function it should try the key instead. Child index is
no good as it could change between renders. Should be tagged as Bug.

**Comment by alexlande** [comment]
@ianobermiller: React is going to remove string-based refs in favor of first class ones, right? I wonder if it makes sense to deprecate `ref` for Radium element identification and only recommend `key` moving forward.

**Comment by ianobermiller** [comment]
@alexlande I don't know of any plans to deprecate string refs, although I suppose with ES6, callback-based refs are just about as easy, plus they are static analysis (flow) friendly. I'd say for now we just make sure Radium ignores callback refs. We might also consider promoting key to be the first one picked instead of ref, but I don't think it makes a huge difference.

**Comment by alexlande** [comment]
Huh, yeah. I saw this tweet a while back: https://twitter.com/sebmarkbage/status/631158700183552002

I can't find a mention of it anywhere else though, so maybe not worth worrying about until it happens.
