### ISSUE TITLE
Use inline-style-prefixer

### ISSUE THREAD

**Issue by ianobermiller** [FormidableLabs/radium#374]
Instead of Radium's DOM-based prefixer, which does not work on the server, we should use [`inline-style-prefixer`](https://github.com/rofrischmann/inline-style-prefixer), which does prefixing based on user agent (using the same data as autoprefixer). This library will make prefixes rendered on the server identical to those on the client, as long as the user agent is the same.

I'm working with @rofrischmann to clean up the API and reduce the size of the library, but as it stands it will not add too much bulk to Radium, maybe 1k or 2k more.

This will solve a number of issues: #201, #301, #311, #328, #342, #350, #351.

**Comment by alexlande** [comment]
:+1: This makes a ton of sense

**Comment by stevewillard** [comment]
This looks awesome! Excited for this.

**Comment by geoRG77** [comment]
@ianobermiller Hey Ian, how it goes with this? Any help needed? I'm really excited about this feature as it will finally fix the server rendering issue of our isomorphic app.

**Comment by Simonify** [comment]
Also interested in the status of this and how universal rendering should be handled with regards to Radium.

I'm currently passing the user agent as a `context` prop throughout my app and then using a custom prefixer plugin that inspects the component (`getComponentField`) to find the user agent string so that it can be used with `inline-style-prefixer`.

While this seems to work, it's a bit messy (though I'm not really sure how else to provide the plugin with the user-agent when it comes to server requests). Any guidance would be appreciated.

**Comment by ianobermiller** [comment]
It's almost ready. Chime in on #397 if you'd like to help me solve the configuration issues that are preventing me from landing it. @Simonify, ideally you don't have to create such a workaround just to prefix correctly!

**Comment by vijayrawatsan** [comment]
:+1: for this feature.
