### ISSUE TITLE
Focus is getting stuck, but only on one element

### ISSUE THREAD

**Issue by natew** [FormidableLabs/radium#410]
I have two buttons side by side and both use the same focus styling. For some strange reason, all buttons but the first one get "stuck" in focus. For some reason the event doesn't fire to remove it ever.

Here's a video:

https://v.usetapes.com/AIS3nzVHbg

Any ideas why this would be happening?

**Comment by natew** [comment]
Turns out it was `:active`, and this fixes it:

![image](https://cloud.githubusercontent.com/assets/12100/11105649/20b8529e-8885-11e5-8d00-d9fd2200fd5d.png)

**Comment by ianobermiller** [comment]
Oops, I totally broke this a while ago! The mouse up handler should be handling this, but right now if there is more than one item with an active style in the same component it won't.

[This line in `resolve-interaction-styles`](https://github.com/FormidableLabs/radium/blob/c8ff9b81cfb2e4bfbc080f014ea8ba4c7213e7c3/src/plugins/resolve-interaction-styles-plugin.js#L92) should be `if (getState(':active', key) === 'viamousedown') {` instead of `if (getState(':active') === 'viamousedown') {`.

**Comment by natew** [comment]
Oh cool, would love to get off my custom branch! Let me know when released.
