### ISSUE TITLE
Pixel value shorthand on <Style> rules broke in 0.15

### ISSUE THREAD

**Issue by herrstucki** [FormidableLabs/radium#439]
The following code

```js
import React from 'react';
import ReactDOM from 'react-dom';
import {Style} from 'radium';

ReactDOM.render(
  <div className='foo'>
    <Style
      scopeSelector='.foo'
      rules={{
        div: {
          background: 'red',
          width: 100,
          height: 100
        }
      }}
    />
    <div>Yay</div>
  </div>,
  document.getElementById('app')
);
```

used to work in 0.14 (width and height got converted to `100px`) but doesn't anymore in 0.15. Was this intentionally removed? I couldn't find a note in the changelog.

**Comment by ianobermiller** [comment]
This must have broke during the move to `inline-style-prefixer`. We'll either have to resurrect the unitless property checking code or just decide to not support it.

**Comment by ianobermiller** [comment]
Ugh, this was complex and error prone in the previous version (have to strip off prefixes, keep up to date). How about we just warn if any values are numbers, and force you to use strings, adding px yourself if needed or just a plain string in a number (for e.g. z-index).

**Comment by rofrischmann** [comment]
You could check for number values using the following snippet
```javascript
if (!isUnitlessProperty(property) && !isNaN(parseFloat(value)) && isFinite(value) && value !== 0) {
   value = value + 'px'
}
```
where `isUnitlessProperty` was almost taken completely from React itself, see [https://raw.githubusercontent.com/rofrischmann/react-look/develop/src/utils/isUnitlessProperty.js](https://raw.githubusercontent.com/rofrischmann/react-look/develop/src/utils/isUnitlessProperty.js)

You might even consider adding a new prop to the `Style` Component which defines a unit to use e.g. `em` instead of `unit` as default value.

**Comment by deathmood** [comment]
+1 warning isn't enough - so much easier to write just number. And if you do so, code style will be different in plain react styles and <Style />

**Comment by herrstucki** [comment]
Wouldn't this be a good addition to inline-style-prefixer itself @rofrischmann?

**Comment by rofrischmann** [comment]
@herrstucki Thanks for mentioning! It'd not be a problem to add that, but actually this only happens when converting inline-styles to CSS rules as React itself handles number values and converts those to valid 'px' values as far as I know. 
Since inline-style-prefixer is an explicit prefixer for inline-styles this should be handled within Radium's CSS convertion itself.

**Comment by herrstucki** [comment]
@rofrischmann I see, yes that makes sense.

**Comment by herrstucki** [comment]
Nice, thanks! :+1:
