### ISSUE TITLE
display: 'flex' doesn't work on device mode 

### ISSUE THREAD

**Issue by YesaDyuss** [FormidableLabs/radium#467]
style : { 
     display: 'flex' 
}

In inspect form of Chrome browser i got instead of    display: '-webkit-flex'   ->     display: '-webkit-box'  
I am rather new to both React and Radium, so I hope I didn't miss anything obvious.

**Comment by ianobermiller** [comment]
This is likely an [`inline-style-prefixer`](https://github.com/rofrischmann/inline-style-prefixer) issue probably best to post over there. cc @rofrischmann

**Comment by rofrischmann** [comment]
@YesaDyuss Feel free to create an issue at the inline-style-prefixer repo. I'll need exact details of your environment: device, browser (+version), OS (+version) to solve this problem :P

**Comment by YesaDyuss** [comment]
Windows: 10
Browser: Chrome Version 47.0.2526.106
device: Chrome - inspect - toggle device mode

**Comment by ianobermiller** [comment]
@rofrischmann Can't recall, is this fixed in i-s-p 0.6.2?

**Comment by rofrischmann** [comment]
This actually was discussed on an i-s-p issue either, but turned out to not be the prefixers fault, but the fact that changing the device mode to e.g. IE8 would (ofc) use an IE8 userAgent while the underlaying rendering engine (ofc) is still Chrome. Therefore `keepUnprefixed` was implemented as it most likely prevents like 95% of any issues in modern browsers.
But at all it is a development only issue and won't appear on a "real" mobile device.

**Comment by ianobermiller** [comment]
Cool, thanks for the explanation. Closing then!
