### ISSUE TITLE
Autogenerated classes and debugging?

### ISSUE THREAD

**Issue by pstoica** [FormidableLabs/radium#49]
This library seems neat so far! But, I had a few questions, particularly on why there is an emphasis on inline styles and not autogenerated classes.

I noticed the scopable style tag feature, but unfortunately placing style tags in `<body>` does not scope, and the `scoped` property isn't fully supported. And you still have to worry about class collision. Creating those style tags individually per mounted component instance instead of globally managing it also seems problematic (unless I misread it).

Also, how has debugging been working with this? Do inline styles ever collapse in the inspector? Are they easy to ignore? This is the case where autogenerated + debuggable classnames seem helpful; less inspector noise.

Is there any performance/accessibility impact using event handlers vs pseudo attributes?

I'm asking these questions after looking at JSS and react-styles. Just trying to find a good medium for all these ideas. Maybe I'm missing something regarding inline styles as the answer!

Looking forward to this!

**Comment by alexlande** [comment]
Thanks for checking it out! As a preamble, we think JSS and react-styles are really cool approaches.

> I noticed the scopable style tag feature, but unfortunately placing style tags in <body> does not scope, and the scoped property isn't fully supported. And you still have to worry about class collision. Creating those style tags individually per mounted component instance instead of globally managing it also seems problematic (unless I misread it).

The `Style` component isn't quite ready for prime time (hopefully in the next week or so that will change). It doesn't use the `scoped` property because browser-support just isn't there yet. The current implementation is very simple/naive-- it takes a selector string, whatever that might be, and places any styles in the tag under it. That could be used in conjunction with classes or IDs, or by passing in the current component's `data-reactid` attribute.

Our initial recommendation for the `Style` component is going to be to limit usage, because you hit some tough browser repaint issues embedding HTML `style` elements throughout the DOM. We're working on an approach to pull `Style` component content into a single aggregate element at the top of the app.

> Also, how has debugging been working with this? Do inline styles ever collapse in the inspector? Are they easy to ignore? This is the case where autogenerated + debuggable classnames seem helpful; less inspector noise.

I've personally not minded it much, but I spend most of my time navigating through the React devtools Chrome extension. There is definitely some inspector noise in the DOM view, but the tradeoffs-- particularly knowing exactly where the styles for a given component are coming from, have been worth it.

> Is there any performance/accessibility impact using event handlers vs pseudo attributes?

We haven't had any trouble yet. If there was an accessibility problem, I would be the first person to pull the plug on the whole thing :). All React event handlers are delegated, so the performance overhead there is pretty minimal. In our benchmarks we haven't seen any issues.

Re: generated classes in general, we're currently looking toward a hybrid approach. In general, I think that dealing directly with inline styles is easier to reason about (and presents less overhead), but there are definitely situations where generated classes are the right way to go. Some of the big ones are:

- Server-side rendering + media queries
- Server-side rendering + browser states (`:hover`, etc)
- User-generated content (styling all links or headings inside a component)
