### ISSUE TITLE
Radium is growing! This is what we're planning. Discussion thread for new name.

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/radium#504]
The Radium family is growing! The inline style library is going to be joined by a component library. To start, we will release a flexbox-based [grid system](https://github.com/FormidableLabs/radium-component-library/issues/1), followed by a typography toolkit, and form components.

Radium components will follow a set of [core principles](https://github.com/FormidableLabs/radium-component-library/issues/2) including, but not limited to:
- Accessibility is a first-class citizen.
- Inline styles exclusively, wherever possible.
- Getting started should be super simple. We will lower the bar to get started by drawing on principles from the data viz ecosystem [Victory](http://victory.formidable.com/): sensible defaults, live code examples, and providing an aggregator module that you can `npm install` and import individual components from.

We want the Radium brand to be associated at the core with a new way of building user interfaces (inline styles is just the start), and as such, our plan is to use the `radium` github and npm name as the aggregator module. This means moving Radium as it's known today under a name like `radium-style` or `radium-style-resolver`.

The structure would look something like this:

```
radium
  |-radium-style
  |-radium-grid
  |-radium-typography
  |-radium-input
  |-radium-textarea
  |-...
```

We will do our best to ensure this transition is smooth. In practice, it will be small breaking change: `import { Radium } from 'radium'` might become `import { RadiumStyle } from 'radium'`.

Please help us by suggesting a new name for Radium Inline Styles, and let us know of any concerns you may have.

**Comment by paulathevalley** [comment]
Name ideas for the aggregator module: 
`radium-core`
`radium-nucleus`
`radium-heart` 
`radium-bolts`

**Comment by coopy** [comment]
Clarification - `radium` is going to be the aggregator module. We are looking for a new name for what is currently called "Radium" - the inline styles module.

**Comment by prashaantt** [comment]
This is going to be very exciting :+1: 

I have no experience with npm orgs, so I don't know whether it's possible to move the current `radium` package to its own org while retaining the same package name. Assuming it is, I'd be happy to see the core `radium` left alone as it is because none of the suggested options sound very compelling to me (though `radium-core` is nice), and it wouldn't break npm either.

Org-wise, if you feel like, the projects may be structured without the prefix:

```
github.com/radium/radium[*]
github.com/radium/grid
github.com/radium/typography
github.com/radium/input
github.com/radium/textarea
```

while the npm packages will of course bear the full names: `radium`, `radium-grid`, `radium-typography`, and so on.

[*] If you must change the name of the core project, it may look like: `github.com/radium/core`.
