### ISSUE TITLE
Migration helper

### ISSUE THREAD

**Issue by mattborn** [FormidableLabs/radium#56]
I am currently in the process of converting parts of an app to use Radium. The most tedious part of this is changing spinal-case to camelCase, wrapping string values in quotes, removing `px`, etc. as this is the paradigm shift from CSS syntax to JS style syntax:

~~~
width: 100px;  →  width: 100
background-color: #abcdef;  →  backgroundColor: '#abcdef'
-webkit-overflow-scrolling: touch;  →  webkitOverflowScrolling: 'touch'
~~~

Doing this manually takes hours for even a small app, but I’d imagine parsing would take seconds. Would it be appropriate for Radium to include a helper to parse a compiled CSS file since this would reduce the friction of adopting the framework? Or should this be a separate project / addon?

**Comment by alexlande** [comment]
Agree that this would be useful (also quick to put together). Very similar to this: https://github.com/jsstyles/jss/blob/master/bin/cssToJss.js

I think I would lean toward making it a separate project since it's pretty well defined + not directly connected to Radium core.

I can put something together here (or if anyone else wants to feel free). Any ideas on a good API? My first impression is something like this:

```
radium-to-css style.css style.js
```

```
/* style.css */
.btn {
  background: #ccc;
  padding: 10px;
  font-size: 16px;
}

.btn-primary {
  background: orange;
  color: #fff;
}
```

```
// style.js

module.exports = {
  ".btn": {
    background: "#ccc",
    padding: 10,
    fontSize: 16
  },
  ".btn-primary": {
    background: "orange",
    color: "white"
  }
}
```

Then you could import the converted styles, or copy and paste them, or whatever.

**Comment by colinmegill** [comment]
+1 for this, and +1 for making it a new repo

**Comment by alexlande** [comment]
Watch this space: https://github.com/FormidableLabs/css-to-radium

**Comment by alexlande** [comment]
PR for a simple migration CLI is here: https://github.com/FormidableLabs/radium/issues/56

**Comment by mattborn** [comment]
Incredible work, @alexlande. I am going to start using this today.

**Comment by alexlande** [comment]
Finally released https://github.com/FormidableLabs/css-to-radium just now. Should be pretty usable!
