### ISSUE TITLE
Need :before and :after. Rendering extra elements does not provide clearfix

### ISSUE THREAD

**Issue by stephmilovic** [FormidableLabs/radium#563]
I'm trying to clear some list elements. I attempted to use `<i>` in place of `:before` and `:after`. This does not work. Additionally, there is no support for `*zoom: 1;`. Here is what I am attempting to do:

// Clearfix

```
li: {
  *zoom: 1
  ':before': {
    content: '" "',
    display: 'table'
  },
  ':after': {
    content: '" "',
    display: 'table',
    clear: 'both'
  }
}
```

**Comment by ianobermiller** [comment]
The [`visited-plugin`](https://github.com/FormidableLabs/radium/blob/master/src/plugins/visited-plugin.js) could easily be adapted to provide support for `:before` and `:after`, but I'm not sure that we should. Besides clearfix, there really aren't any legitimate uses for `:before` and `:after` with inline styling; it is more clear to just render the element directly and make it explicit, since it is all in JS anyway.

That being said, it would be trivial to create a plugin, say `clearfix-plugin`, that uses `addCSS` to add a `.clearfix {...}` declaration, and then applies that class to elements putting `{clearfix: true}` or something similar in their inline style. I'd consider adding something like this to core Radium.

**Comment by iDVB** [comment]
We've just committed to using Radium on our production project. All is well so far. Thanks!
However, I'm rather shocked that a defined, and example-backed solution for clearfix+radium hasn't been discussed. What is everyone else doing to solve this?

**Comment by ianobermiller** [comment]
One simple solution is to define a .clearfix class in a CSS file and use
that instead. We've talked about pure radium solutions, but haven't yet
added anything. Probably worth adding to the docs.

**Comment by iDVB** [comment]
For sure. Its hard for me to leave the dream of a pure JS solution though. Especially being a traditional developer who had "inline styles BAD" beat into me for years.

I found this... https://gist.github.com/jbmusso/896a389ba707fe583ddc

...but Somehow it just feel like way too much effort for something simple.

We may just end up using flexbox and hopefully avoid the need for a clearfix

**Comment by alexlande** [comment]
Closing this in favor of #510.
