### ISSUE TITLE
Bug: Radium wrapper breaks on ES7 arrow methods

### ISSUE THREAD

**Issue by nbrady-techempower** [FormidableLabs/radium#738]
The current version of Babel is not supporting decorators until the change in decorators is finalized with  TC-39. Because of this I've done this in react:

``` javascript
class LandingHero extends React.Component {
<code here>
}
export default Radium(LandingHero);
```

This works fine, unless render is an arrow method like so:

``` javascript
class LandingHero extends React.Component {
  render = () => <div>Something</div>;
}
export default Radium(LandingHero);
```

Then I get the following error:

``` error
Uncaught TypeError: Cannot call a class as a function
```

Of course the error is coming from the babel runtime compiler and not radium specifically but I was wondering if there was something that could be done here to support this in the future.

**Comment by ianobermiller** [comment]
> The current version of Babel is not supporting decorators

Not really true; the current version of Babel is a generic compiler; the standard presets do not include decorators, for the reason you mentioned. But, there is of course a plugin that does, and I thought the class part of the proposal is fairly stable.

Anyway, why are you using an arrow function on the render method? It has no value, but add syntactic and runtime overhead.

Finally, to get to the core of the issue, it has something to do with the way babel generates code, but I don't really know what the solution is: https://phabricator.babeljs.io/T1161

**Comment by nbrady-techempower** [comment]
I'm using arrow functions in all of my class methods for `this` binding. I've seen the runtime benchmarking tests and I'm not really concerned yet as this isn't an app for production before ES6 is standard.

As for the plugin: http://babeljs.io/docs/plugins/transform-decorators/ ?

**Comment by ianobermiller** [comment]
Yea, the legacy version mentioned on that page.

**Comment by faroe228** [comment]
I was getting the same error as nbrady-techempower ( Uncaught TypeError: Cannot call a class as a function ) and I was not using arrow functions or decorators ( this only happens when I use production mode - it also works fine when using HMR ).   I was using quik to generate a single html file.

https://github.com/satya164/quik#generating-a-sharable-single-html-file

Just discovered another oddity, when I use a button instead of a muicss Button, problem goes away. I browsed the muicss button.jsx source I don't see any use of decorators.

https://github.com/muicss/mui/blob/master/src/react/button.jsx

**Comment by dmoskovtsov** [comment]
Is there anything we can do about it?

**Comment by ryan-roemer** [comment]
Can anyone confirm if this is still an issue? I think we support everything for render methods that any other React library would at this point...

**Comment by jimsalabim** [comment]
@ryan-roemer yeah, this is still an issue.

I'm at version `0.22.1` and trying something like this:
```
class Foo extends Component {
    render = () => {
        const styles = getStyles(this.props, this.state);
        return (
            <div style={ styles.foo } />
        );
    };
};
const getStyles = (props, state) => {
    return {
        foo: {
            color: 'red'
        }
    };
};
const mapStateToProps = (state, ownProps) => {
    return {};
};
const mapDispatchToProps = (dispatch) => {
    return {};
};
export default connect(mapStateToProps, mapDispatchToProps)(Radium(Foo));
```
With error: `Uncaught TypeError: Cannot call a class as a function`

This will work:
```
    render() {
        const styles = getStyles(this.props, this.state);
        return (
            <div style={ styles.foo } />
        );
    };
```

**Comment by ryan-roemer** [comment]
Verified and opened up reproduction repository at: https://github.com/FormidableLabs/radium-arrow-render-738

Not sure when we'll have a chance to dig our heels in on this more, but we've verified and captured the issue for now...

**Comment by ryan-roemer** [comment]
Updates..

## The good news

Updating the `isStateless` check to something like:

```js
function isStateless(component: Function): boolean {
  const proto = component.prototype || {};

  return !component.isReactComponent && !proto.isReactComponent &&
    !component.render && !proto.render;
}
```

works well to avoid the error and detect if a component is used (however `render` is define)

## The bad news

This arrow function approach breaks Radium's fundamental enhancer: https://github.com/FormidableLabs/radium/blob/master/src/enhancer.js#L121-L224 -- in abbreviated form we have:

```js
  class RadiumEnhancer extends ComposedComponent {
    constructor() {
      super(...arguments);

      this.state = this.state || {};
      this.state._radiumStyleState = {};
      this._radiumIsMounted = true;
    }

    render() {
      const renderedElement = super.render();
      // DO RADIUM STUFF
      return element;
    }
```

The problem is that `RadiumEnhancer.prototype.render` is being overwritten by the Component class with a static arrow method in its constructor with an internal `this.render = function () {}`. So the radium stuff is never called.

I'm guessing the same applies to all methods in the Enhancers.

We may just end up not supporting arrow methods because this is going to be a hacky fix if anything... 

/cc @alexlande
