### ISSUE TITLE
Media query breakpoint does not work

### ISSUE THREAD

**Issue by 123ndy** [FormidableLabs/radium#756]
I have a form with an input field and a button. The input field changes at 1441px, but the button does not change on 1441px. I had to set it to 1442px for it to change. 

Am I doing something​ wrong, or can it be a bug?

      emailInput: {
        width: '46vw',
        height: '63px',
        fontFamily: 'MaisonNeueLight',
        fontSize: '1.0625rem',
        color: '#7d7d7d',
        textDecoration: 'none',
        borderRadius: '3px',
        borderStyle: 'none',
        marginRight: '10px',
        backgroundColor: '#f0f0f0',
        padding: '0em 0em 0em 1em',
        transition: 'background-color 0.2s ease-out',
        '@media (min-width: 641px)': {
          width: '25vw',
        },
        '@media (min-width: 1025px)': {
          width: '25vw',
          height: '66px',
          marginRight: '20px',
        },
        '@media (min-width: 1441px)': {
          height: '75px'
        },
        ':focus': {
          outline: 'none',
          backgroundColor: '#f5f5f5',
        }
      },
      submitButton: {
        padding: '0px',
        width: '24vw',
        height: '63px',
        fontFamily: 'MaisonNeueLight',
        fontSize: '1.0625rem',
        color: colors.text.white,
        textDecoration: 'none',
        borderRadius: '3px',
        borderStyle: 'none',
        backgroundColor: colors.section.black,
        color: 'white',
        appearance: 'none',
        transition: 'opacity 0.1s ease-out',
        '@media (min-width: 641px)': {
          width: '110px',
        },
        '@media (min-width: 1025px)': {
          width: '10vw',
          height: '66px'
        },
        '@media (min-width: 1442px)': {
          height: '75px'
        },
        ':focus': {
          outline: 'none'
        },
        ':hover': {
          opacity: '0.7',
          cursor: 'pointer'
        },
        ':active': {
          opacity: '0.6'
        }
      }

**Comment by jmcriffey** [comment]
I believe issue here is that Radium is generating a single class name for both the input and button to share. Since the media query is only defined once by Radium, the 1025px media query for the button is defined last and takes precedent. 

@alexlande I believe that is a bug that we can address by generating unique class names per object instead of reusing them, correct? Is that the goal of https://github.com/FormidableLabs/radium/pull/635, or is that a different issue?

@123ndy You can solve your immediate problem by forcing Radium to generate unique class names. You can add any attribute that remains constant to the button's media query to achieve that. Maybe something like: 

```js
'@media (min-width: 1441px)': {
   color: "white",
   height: '75px'
 }
```

Just in case, here is a minimal repro with color (easier to see): https://jsfiddle.net/nb0yoysx/

**Comment by alexlande** [comment]
Yep, this is something that #635 is meant to address.

**Comment by 123ndy** [comment]
Thank you @jmcriffey! Setting the `height: 'white'`, solved it.

Keep up the good on this awesome library guys!
