### ISSUE TITLE
Eliminate getBrowserStateEvents and buildStyles

### ISSUE THREAD

**Issue by ianobermiller** [FormidableLabs/radium#80]
I've been thinking a lot about how we can simplify the API surface of Radium. As we've already seen from #76, it can be burdensome to remember to add getBrowserStateEvents and then wire up your own handlers. It is also not ideal to have to call buildStyles. Further, Radium only allows you to style a single element in the component (correct me if I'm wrong).

The only way to simplify this API is by somehow wrapping the render functions. There are a ton of ways to accomplish this, and they don't necessarily require monkeypatching createClass. I've been playing around with my own inline style helper, jokingly named Cesium: https://github.com/ianobermiller/nuclearmail/blob/master/src/js/Cesium.js. The main goals of Cesium are to:
- Be compatible with normal inline styles (you only include Cesium if you want interactivity or vendor prefixing)
- Be as simple and foolproof as possible to use

The syntax I'm currently using looks like this, simplified for the example. Note that the only differences between using normal inline styles are: 1) `Cesium.wrap` inside of `createClass`, and 2) `':hover'` prop with a style object value (this is basically a more concise version of `modifiers: { hover: { ... } }`

```js
var Button = React.createClass(Cesium.wrap({
  propTypes: {
    onClick: PropTypes.func,
  },
  _onClick() {
    this.props.onClick && this.props.onClick();
  },

  render(): any {
    return (
      <button type="button" style={styles.root} onClick={this._onClick}>
        {this.props.children}
      </button>
    );
  }
}));

var styles = {
  root: {
    background: Colors.gray1,

    ':hover': {
      background: Colors.gray1.darken(5),
    },

    ':active': {
      background: Colors.gray1.darken(10),
    },
  },
};
```

The main idea here is that you don't need `getBrowserStateEvents` and `buildStyles`. `Cesium.wrap` wraps the `render` method, walks the result of the original render, and updates styles/adds handlers as appropriate.

In the simple case of one interactive component, you don't need anything more than this. If you want to style multiple elements in a single component, you have to specify a unique `ref` or `key` for each one, to correlate the interactive state from the event handlers.

I'd love to see these ideas make their way into Radium. Thoughts?

**Comment by alexlande** [comment]
Generally-- I like this a *lot*. Moving this direction would solve a lot of our issues, particularly our verbosity and the difficulty in applying browser states to multiple elements in a single component (without making them components themselves).

I don't really have strong opinions on `:hover` vs `states: [{ hover: {} }]`. That works for me if people think it would be a nicer authoring experience.

One thing-- you're including `:hover`, etc as properties, rather than as an array of objects. We do the `[{ hover: {} }]` thing for correctness, despite the fact that all browsers iterate through objects in the order that they're declared (except when there are numerical keys).

This isn't that related, but I still wonder if we should go back to the old, non array way of declaring modifiers, despite being technically incorrect. All of those curly braces kill me:

```js
modifiers: [
  {
    type: {
      primary: {},
      warning: {}
    }
  }
]
```

vs

```js
modifiers: {
  type: {
    primary: {},
    warning: {}
  }
}
```

**Comment by alexlande** [comment]
This would also help us move away from our over-reliance on mixins: https://github.com/FormidableLabs/radium/issues/65

**Comment by kenwheeler** [comment]
That is a lovely way to get around mixins.

**Comment by ianobermiller** [comment]
alexlande, good point about object iteration, except that its even worse than you thought; I was just applying them in a fixed order (always focus then hover then active). I think at this point it is OK to rely on object iteration order, as you said.

**Comment by ianobermiller** [comment]
Also, I like `':hover'` because it is very unlikely to clash with any name you might want to use. Even though `hover` is nice and much easier to type, it is more likely to clash (be done accidentally) and less obvious IMO.

**Comment by ianobermiller** [comment]
Finally, if you are on board with this, I'd be willing to submit a PR that gets us some of the way there. We just have to choose the syntax (and there are many options). If everyone is on board with 'React.createClass(Radium.wrap({ ... }))' I'll take a shot with that.

One issue with this syntax is that it doesn't really work for ES6 classes. To be honest though, I think that is fine. It works very well with createClass, and we can come up with something different for classes when they are properly supported.

**Comment by alexlande** [comment]
Yeah, I'm good with going this direction. I'm not 100% convinced about replacing `states` with `:hover`, etc, but we can bikeshed on that later.

Re: ES6 classes, why not extend extend `React.createClass` rather than wrapping it? That would be closer conceptually to how we'll need to handle it with ES6 classes, right?

**Comment by ianobermiller** [comment]
What do you mean by extend rather than wrapping? Subclassing ReactComponent with classes would not be ideal, since you'd have to call super() with the result of your render, or use a different method name, like radiumRender.I think we should solve classes separately.

**Comment by alexlande** [comment]
Fair enough. Let's move forward with this. Can we hold off on changing `states` syntax until after though? Would like to address this before changing style object syntax too much.

One other thing for this-- we'll need an optional method for applying styles to handle the `additionalModifiers` and `excludeProps` parameters from `buildStyles()`: https://github.com/FormidableLabs/radium/tree/master/docs/api#additionalmodifiers

(Will leave a comment on #82, but would likewise like to re-evaluate that one after the wrap behavior is in.)

**Comment by gavacho** [comment]
I expect to use the `additionalModifiers` feature quite a bit. Would y'all consider following syntax along with these other changes (which all look great).

```jsx
<div style={this.styles.myElement({ active: this.state.isActive })} />
```

I'm proposing that the wrapper be used to also convert `this.styles` from a simple data structure into something with functions that can take `additionalModifiers` and `excludeProps`

**Comment by ankitshah2787** [comment]
@ianobermiller In your cesium implementation, do you think it makes sense to call your handlers first to do hover, active, focus styles and then call user defined handlers? I am worried that if the user defined handler is doing some heavy calculation inside, users would see a lag in styles getting applied.

**Comment by ianobermiller** [comment]
If they are doing heavy calculation the order won't matter; the styles
won't get applied until that thread of execution ends anyway, since JS is
single threaded. You might want to call them after, though, so they can use
the callback version of setstate and see any states that Cesium updated.

**Comment by benoneal** [comment]
Styling multiple elements within a single component is easy. Your styles object can just have different keys for each element, then inside your render method, you just apply the styles to each element like: ```<div style={ this.buildStyles(style.elementIdentifier) } />```

**Comment by alexlande** [comment]
Done!

**Comment by benoneal** [comment]
I won't lie, I'm really disappointed by the direction of this new API. It removed the need for getBrowserStateEvents() and declaring modifiers and states in your style object at the expense of now having to hand-hold all modifiers and non-browser states explicitly in your render, and making it much, much, much more cumbersome and verbose to style multiple elements within a single component. Making it a wrapper instead of mixins also makes it harder and more cumbersome to extend functionality, such as vendor prefixing, which was previously as simple as creating a new mixin to wrap radium's. Have any of you guys tried to actually use radium to manage styles throughout a complete real world app? Where some atomic components like buttons and inputs can have several interacting modifiers, plus state, plus mediaqueries, all of which affect multiple sub elements like icons, labels helper text, tooltips, wrappers, in addition to the core element itself? 

When I get to work I'm going to post a real world example of a single atomic component from our production app which highlights how fantastic the old API was, and how much of a nightmare this new API would be.

**Comment by alexlande** [comment]
@benoneal: I'm sorry to hear that. Could you open a new issue with the example you mentioned? It would be really helpful to see some details and try to figure out how we can make things better.

The new API makes the authoring experience quite a bit different, but we definitely don't want to make any existing use cases more difficult because of it.

**Comment by ianobermiller** [comment]
@benoneal I'll check out your example in #123, I'd love to see how we can further streamline it. The new API has a lot of advantages over the old one, mainly in that it is much simpler to use, and has less gotchas/surprises than the old API. The new functionality cannot be accomplished with a mixin alone, otherwise I would definitely have done so for the createClass version. 

We will be adding vendor prefixing soon, but I'd also like to hear about which other extension points would be useful. Something generic like "let me modify the style right before you pass it to React" would probably be really useful and unlock a lot of scenarios.
