### ISSUE TITLE
Does Radium ever use window.matchMedia instead of @media?

### ISSUE THREAD

**Issue by Cryza** [FormidableLabs/radium#849]
Radium makes it one of its key arguments that there is no CSS in use but only inline styles. However I was not able to produce responsive styling with breakpoints that did not involve the CSS `@media` query which was inserted into Radium's root-level Stylesheet.

I did see some code involving `window.matchMedia` within `resolve-media-queries.js`, but I can't seem to understand when Radium would ever use that over a classic `@media` query. Is there a way to get Radium to completely leave out classes and use `window.matchMedia` instead? The plugin says something about "top-level media queries", but aren't all media queries top-level?

**Comment by alexlande** [comment]
@Cryza Radium originally used `matchMedia`, but replaced it with the current `@media` syntax due to issues with server side rendering and `matchMedia` (namely that we didn't know what the current media query was for SSR so there were style mismatches).

Unfortunately, there are issues with our `@media` implementation too, but moving forward I don't expect that implementation to change back to `matchMedia`.
