### ISSUE TITLE
stateless component style getting wrong

### ISSUE THREAD

**Issue by EasonWang01** [FormidableLabs/radium#850]
If I have two parent component,both import the same stateless component,then the first one parent component giving style as props pass down to the stateless component in order to custom the stateless component style.

Another parent component not giving style as props pass down,but this parent component will memorize this style change of the stateless component from another parent component.

what might cause this problem?

```
const Modal = (props) => {
   return (
     <div>
        <div style={Object.assign(style.blackContainer,props.blackContainer)}>
     </div>
      <div style={Object.assign(style.whiteBox,props.whiteBox)}>
        {switchModal(props.modal,props.context)}
      </div>
    </div>
  );
};

```

**Comment by alexlande** [comment]
Hi @EasonWang01, I believe the issue here is your `Object.assign` usage-- the first object passed to `Object.assign` is mutated, so in this case you're modifying the `style.blackContainer` and `style.whiteBox` objects when your component renders, which would cause other instances of this component to use the same mutated styles.

To prevent this, pass an empty object in as the first argument to `Object.assign` (this is a good idea a lot of the time to prevent accidental data mutations):

```js
Object.assign({}, style.blackContainer, props.blackContainer);

...

Object.assign({}, style.whiteBox, props.whiteBox);
```
