### ISSUE TITLE
zIndex doesn't work

### ISSUE THREAD

**Issue by PendletonJones** [FormidableLabs/radium#851]
Does nothing, tried "z-index" "zIndex" and "ZIndex" but it doesn't create the property on the element.

**Comment by maurolionel** [comment]
Are you sure? It's working fine for me in this example http://www.webpackbin.com/41CLN2Klf as "zIndex" (it sets the "z-index" to 5 when subtitle its hovered).
Can you make a bin on http://www.webpackbin.com/ showing the bug?

What is not working is the overrided property "backgroundColor" inside the ":hover" state of the media querie. This is because is not posible to override the generated "!important" of the media queries.
I think i should open an issue about this. Know something about this?

(Sorry if my english is not right enough, i'm from Argentina!)

**Comment by alexlande** [comment]
Yep, not able to repro this one so going to close. Please chime in if you're seeing this issue and have a working example.

@maurolionel: Yeah, the media query ordering is a big problem. See #635 for more information on that.
