### ISSUE TITLE
Recommendation: use flex-basis of auto instead of 0%

### ISSUE THREAD

**Issue by ffxsam** [FormidableLabs/radium#866]
By default, Radium translates `flex: 1` to `flex: 1 1 0%`. This causes a problem in IE11, which can be remedied by using the JS style `flex: '1 1 auto'` instead.

Compare this fiddle on IE11 vs any other browser:
https://jsfiddle.net/ffxsam/ymk93f3v/

(side note: this might only be an issue when the container's `flex-direction` is set to `column`)

**Comment by tshinnic** [comment]
BTW: There are problems using 'auto' with flexbox on Chrome, because they interpret the meaning of the specification's term "indeterminate value" differently (and less usefully) than Edge/IE/FF.  There are circumstances where 'auto' will cause Chrome to collapse inner boxes to zero height.  Strangely, everyone interprets '0%' as a "determinate value", and Chrome goes through different code paths and ends up with the correct expanded value for the inner box.  It is a spec nit, and I'd run out of time to pursue it, but Chrome's official recommendation (back several months) was "just use 0%".

So it may not be as simple as "use the specification's constantly shown 'auto'".  Logic may not apply here, cuz browsers...

**Comment by alexlande** [comment]
Radium doesn't modify styles that are applied to it (outside of prefixing via inline-style-prefixer), and I think normalizing flex bugs would be out of scope for the library. Here's an example of this behavior in plain JS to demonstrate: http://jsbin.com/fixujo/edit?html,js,console

Definitely annoying though! Here are some more details on this issue: https://github.com/philipwalton/flexbugs#6-the-default-flex-value-has-changed
