### ISSUE TITLE
@media queries adding !important

### ISSUE THREAD

**Issue by lightninglu10** [FormidableLabs/radium#877]
Hey guys, my @media queries are unexpectedly adding !important to the CSS property.

This messes up my flow as I can't add !important in react inline styles.

I don't always want @media queries to take precedent. is there a fix for this?

**Comment by stefvhuynh** [comment]
I believe adding `!important` is expected behavior (https://github.com/FormidableLabs/radium/blob/master/src/plugins/resolve-media-queries-plugin.js#L56). Media query rules are all pushed into a `<style>` tag at the bottom of the root element and I believe the only way to override the inline styles that radium puts into an element tag is by adding `!important`.
