### ISSUE TITLE
Media queries sometimes generating in wrong order

### ISSUE THREAD

**Issue by jawinn** [FormidableLabs/radium#879]
The generated styles from Radium for nested media queries (mobile-first approach with increasing min-widths), are sometimes generating in the wrong order in an unexpected and unpredictable way. 

Example 1: 
Generates in the wrong order so that the 768px breakpoint is overriding the 1024 breakpoint at large screens, giving 20px size for the "text" element at screen sizes greater than 1024. Whereas the "largeText" element has the right order and sizes:

```  
text: {
    '@media (min-width: 768px)': {
      fontSize: '20px',
      lineHeight: '32px'
    },
    '@media (min-width: 1024px)': {
      fontSize: '18px'
    }
  },
  largeText: {
    '@media (min-width: 768px)': {
      fontSize: '20px',
      lineHeight: '32px',
      marginBottom: '60px',
      paddingRight: '45%'
    },
    '@media (min-width: 1024px)': {
      fontSize: '18px'
    }
  },
```

Example 2:
Take the same block of styles and add line-height to the first 1024 statement, and this will generate things correctly. The "text" element will have the correct 18px font size at screen sizes larger than 1024:

```  
text: {
    '@media (min-width: 768px)': {
      fontSize: '20px',
      lineHeight: '32px'
    },
    '@media (min-width: 1024px)': {
      fontSize: '18px',
      lineHeight: '32px'
    }
  },
  largeText: {
    '@media (min-width: 768px)': {
      fontSize: '20px',
      lineHeight: '32px',
      marginBottom: '60px',
      paddingRight: '45%'
    },
    '@media (min-width: 1024px)': {
      fontSize: '18px'
    }
  },
```

What's going on here? I can see in the generated CSS that one is combining the CSS in the same statement for some reason (nested within different elements), resulting in the wrong order. So the 768 breakpoint !important is taking precendence over the 1024 breakpoint.

Generated styles:
https://gist.github.com/jawinn/3d296147e5cf2904b2fbd4b019af96e2

**Comment by stefvhuynh** [comment]
This is because the `StyleKeeper` adds media query css to the page in the order that it is received (the order the components are arranged). If there is a rule that is duplicated, it skips over it (https://github.com/FormidableLabs/radium/blob/master/src/style-keeper.js#L31). In your case, there is a duplicate font-size rule (`fontSize: '18px'`) that should be rendered beneath your `min-width: 768px` media query, but it is omitted because the rule has already been added by a previous element. After an initial look at this problem, I believe the fix for this would involve getting the `StyleKeeper` class to arrange media query rules in ascending order.

**Comment by jawinn** [comment]
What we ended up doing to get around this was to specify a max-width along with every min-width media query; e.g. (min-width: 768px) and (max-width: 1023px), and duplicating any styles needed between different sets of media queries. Not ideal, but it works.

**Comment by alexlande** [comment]
@jawinn: thanks for the extra context on this one, and sorry for the trouble. Closing this in favor of #790 which has more discussion on this topic.
