### ISSUE TITLE
[Question] How dynamically load theme

### ISSUE THREAD

**Issue by saeedjalali1** [FormidableLabs/radium#910]
Hi, first thanks for awesome packages. I'm trying to make an application that users can choose favorite theme from admin panel. In the admin panel we show some theme ( theme is only style ) that implement it before. In my case when user change the theme and save setting, the app style changed. 
also we get theme info or style from the rest api. On the other hand for specific reason such as SEO friendly we decided to write app with server side rendering. 
How to do this with your packages? 
Thanks a lot.

**Comment by alexlande** [comment]
Hi @saeedjalali1, you might check out https://github.com/azazdeaz/react-theme for some ideas. In Radium, styles are just data, so you can pass them around as props, or write higher order components to toggle them based on a chosen theme. It's hard to outline specifics because it will depend a lot on your particular app, but hopefully that library will help (or at least the source might give you some ideas on how to implement something similar).
