### ISSUE TITLE
Why babel-* modules are dependencies instead of devDependencies in package.json?

### ISSUE THREAD

**Issue by mondaychen** [FormidableLabs/radium#913]
If a user is using a different version of babel in their package.json, this may cause error

**Comment by ryan-roemer** [comment]
There are two different types of dependencies that Radium supports:

1. `git` based dependencies. In this case, we don't commit `dist/` to source, so it needs to be built from scratch, which means `babel-*` dependencies. A `git` dependency uses https://github.com/FormidableLabs/radium/blob/master/package.json which you're looking at.
2. `npm` based dependencies. In this case, we publish `dist/` to the npm registry so don't need to rebuild it. Because in this case we don't need the `babel-` deps, we rewrite `package.json` as to not included them on publishing (not committed to source) via a bespoke script. (Side note -- we'll be upgrading this soon to use the https://github.com/FormidableLabs/publishr tool which is built explicitly to support this use case). If you look at https://unpkg.com/radium@0.19.1/package.json, you'll see a much more terse `dependencies` (and we have a ticket for [removing `rimraf` from prod deps](https://github.com/FormidableLabs/radium/issues/894)):

```js
  "dependencies": {
    "array-find": "^1.0.0",
    "exenv": "^1.2.1",
    "inline-style-prefixer": "^2.0.5",
    "prop-types": "^15.5.8",
    "rimraf": "^2.6.1"
  },
```

Hope that clears it up!

**Comment by mondaychen** [comment]
Thanks for the details explanation!
