### ISSUE TITLE
Stop recommending decorators

### ISSUE THREAD

**Issue by alexlande** [FormidableLabs/radium#924]
Let's update the docs to suggest wrapping with Radium the old fashioned way: `Radium()`. The decorators proposal has been going through some changes, now there are two Babel plugins depending on if you want the new or the legacy behavior, and the whole thing is getting a little more complicated.

Plus, functional components have become much more popular since we introduced the decorator syntax, and it's simpler to just refer to one way of applying Radium that will work for any component.

**Comment by mikeaustin** [comment]
Random comment: I like Babel, ES6, ES7 and all that, but I pause when a library uses decorators. It's just one more thing for people to learn when working on an existing code-base. I also love higher-order components. I feel decorators will eventually be popular, but right now it seems a bit early.

All in all, I think the fewer dependencies, the better. BTW, I got here because I was looking at Material-UI and read how they started using inline React styles, but want to go back to CSS. If I understand how Radium works, it sounds like the JSX/HTML equivalent: Radium/CSS. Would that be correct. Oh, also, what about JSS? How does it compare?
