### ISSUE TITLE
SVG?

### ISSUE THREAD

**Issue by colinmegill** [FormidableLabs/radium#94]
Thoughts? Will we ever populate SVG attributes? Specifically thinking data viz. See: 

http://nicolashery.com/integrating-d3js-visualizations-in-a-react-app/

& 

https://leanpub.com/reactd3js

**Comment by colinmegill** [comment]
In the Nicholas Hery article, it would be something akin to `this.d3_prep` instead of build styles. In d3, constructing svg looks like this: 

![screenshot 2015-03-21 23 58 52 1](https://cloud.githubusercontent.com/assets/1770265/6768402/69c2200e-d026-11e4-8904-7ed9c4b25eb6.png)

**Comment by alexlande** [comment]
I don't see directly applying attributes to SVGs becoming part of Radium core, but you could use Radium to resolve what those attribute values should be today (as if they were CSS properties).

Some kind of library for applying attributes to SVGs based on an object structure sounds useful, but wouldn't need to be tied to Radium. Could be completely independent.

**Comment by ianobermiller** [comment]
I don't think there is anything actionable for Radium core; if this fits as an addon, we could reopen. Since Radium's core value is in emulating pseudo classes like `:hover`, and such pseudo classes don't make sense in the context of SVG attributes, I don't think this is Radium's territory. Radium can already handle the `style` attribute of SVGs anyway.
