### ISSUE TITLE
Weird problem with meteor 1.7 / es6 classes and binding of this in constructor

### ISSUE THREAD

**Issue by dobesv** [FormidableLabs/radium#999]
When trying to upgrade our app to meteor 1.7 we get some really weird behavior.

It seems like the value of `this` in the constructor is not the same `this` that is used later on in `render`.  As a result, if you have bound your methods to `this` using arrow syntax or `this.foo = this.foo.bind(this)`, it only has access to the props at component creation time.

I have created a reproduction over here in the `react` branch of my fork of `meteor/todos`: https://github.com/dobesv/todos/tree/react

Note that in https://github.com/dobesv/todos/blob/react/imports/ui/components/TodoItem.jsx I have added some boolean strings to the display, indicating whether the values of `this.props.editing` are the same between the bound method and the render method.

If I remove `Radium` from that component, the problem goes away.

**Comment by dobesv** [comment]
Looking at the code, I think it might be this rather evil piece of code here:

```
  if (isNativeClass(ComposedComponent)) {
    // Manually approximate babel's class transpilation, but _with_ a real `new` call.
    ComposedComponent = (function(OrigComponent): constructor {
      function NewComponent() {
        // Ordinarily, babel would produce something like:
        //
        // ```
        // return _possibleConstructorReturn(this, OrigComponent.apply(this, arguments));
        // ```
        //
        // Instead, we just call `new` directly without the `_possibleConstructorReturn` wrapper.
        const source = new OrigComponent(...arguments);

        // Then we manually update context with properties.
        copyProperties(source, this);

        return this;
      }

      inherits(NewComponent, OrigComponent);

      return NewComponent;
    })(ComposedComponent);
  }
```

This seems to be copying properties after running the constructor, which assumes that there are no references to the original object inside the properties of the object.

**Comment by dobesv** [comment]
I'm not totally sure what the reasoning behind that code was, but I wonder if it should have preserved the `this` binding on any methods its copies, or perhaps just any react lifecycle methods.

**Comment by dobesv** [comment]
The reason this used to work in meteor 1.6 is that they used to transpile classes with babel, but now they emit the class syntax as-is for the runtime environment (e.g. the browser) to handle.  So Radium now sees a "native" class and that sketchy logic is used.

**Comment by ryan-roemer** [comment]
Here's the background for why we do the native class detection (it's because we use inheritance and babel inheritance plays very poorly with a target native ES class in Node / supported browser platforms): https://github.com/FormidableLabs/radium/issues/576

The PR with this fix is at: https://github.com/FormidableLabs/radium/pull/936/files . You're welcome to propose an alternate logic that still passes all the regression tests that PR added.

If someone can't provide a complete fix, a good first step is to open a PR with a series of failing regression tests (either client-side or Node-side, as we test and support both), so that the actual "bug" is captured for now. Thanks!
